# Generated by Django 4.1.3 on 2023-05-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_post_user_alter_post_description_alter_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column1_data', models.CharField(max_length=200)),
                ('column2_data', models.TextField(max_length=200)),
                ('table_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('column1_name', models.TextField(max_length=200)),
                ('column2_name', models.TextField(max_length=200)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
